version: '3.7'
services:
  hastunnel:
    image: nickadam/hastunnel:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 8081
        published: 8081
        protocol: tcp
    environment:
      HASTUNNEL_CONFIG: |
        services:
          service1:
            listen_port: 8080
            backends:
              - www.google.com:443
              - drive.google.com:443
          service2:
            listen_port: 8081
            backends:
              - portal.office.com:443
              - portal.microsoft.com:443
